site_name: ML

nav:
  - 'index.md'
  - 'linear_regression.md'
  - 'gradient_descent.md'
  - 'logistic_regression.md'

theme:
  name: material
  font:
    text: Roboto
  features:
    - navigation.expand
    - toc.follow
    - toc.integrate
    - navigation.top
    - content.code.annotate 

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      accent: light blue
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: cyan
      accent: cyan
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  icon:
    repo: octicons/mark-github-16

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

repo_url: https://github.com/squidfunk/mkdocs-material

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://twitter.com/squidfunk

copyright: Copyright &copy; 2022 ML Repository